### ISSUE TITLE
有没有像xposed api中hook某个方法的代码，小白没文档写的老有问题 

### ISSUE THREAD

**Issue by orzlenmo** [Thehepta/Rxmodule#1]
是下面这样写法吗？我写出来，应用再某宝上会卡死闪退，不知道为啥
`
object LoadEntry {

    @JvmStatic
    fun Entry(context: Context, source: String, argument: String?) {
        Log.e("hook", "Entry-----111")
        if (!isMainProcess(context)) {
            return
        }
        Log.e("hook", "Entry---context-${context.packageName}")
        LogUtil.i("ensureInitialized")
        Pine.ensureInitialized()
        hookAppText(context)
    }

    //目前只需要这个函数，注入的时候修改目标MainActivity 的status的值
    private fun hookAppText(context: Context) {
        LogUtil.i("hookAppText")
        val textViewClass: Class<*> = context.classLoader.loadClass("android.widget.TextView")
        val setTextMethod = textViewClass.getDeclaredMethod(
            "setText",
            CharSequence::class.java,
            TextView.BufferType::class.java,
            Boolean::class.javaPrimitiveType,
            Int::class.javaPrimitiveType
        )
        Pine.hook(setTextMethod, object : MethodHook() {
            override fun beforeCall(callFrame: Pine.CallFrame?) {
            }

            override fun afterCall(callFrame: Pine.CallFrame) {
                LogUtil.e("afterCall Text:${callFrame.method.name}")
            }
        })
    }
}`

**Comment by Thehepta** [comment]
你这个应该是有问题的，rxposed 注入，目前应该只能支持java，kt这个静态类我记得是不一样的。这个框架只提供注入的，不提供hook，好好看看文档，如果是小白不建议使用这个

**Comment by orzlenmo** [comment]
Lsposed脚本我会写一些，但是原理不是特别懂，有些应用会检测lsposed，比如taobao，所以想用你这个，研究两天了，上面kt项目跑起来注入式没问题的，跑起来都正常走hookAppText方法了，只是一但我引入你的pineCore 然后用里面的Pine.hook方法，他也能hook走到afterCall，只不过我一旦往afterCall回调里加逻辑，app打开十几二十秒就自动闪退，我看了很多遍文档。所以想问下，这个框架有没办法替代lsposed呢，最主要就是hook某个方法加入逻辑。如果没有的话我就不研究了？

**Comment by Thehepta** [comment]
我觉得你需要验证一下是pine框架在你的手机上有问题，还是app本身有对抗，你找个正常app试一下吧

**Comment by orzlenmo** [comment]
有的APP完全没问题，大部分是有问题的，要么卡死，要么直接闪退，连系统的天气app都会卡死，不太像是对抗，感觉就是pineCore兼容问题，我主要试了这个taobao的。十几秒以后直接闪退，我截图了闪退的日志，能帮我看看最好。我的系统miui14，android13的，代码就是上面那个代码。能不能有实现hook方面的方案链接发我下，那就太感谢作者了
![{D3873D61-1CFB-42c7-8527-2BA02BFEF480}](https://github.com/user-attachments/assets/62e8eb8a-0059-4744-8476-0b394da9ac1d)

**Comment by orzlenmo** [comment]
我试了下换成activity  的onCreate方法没有闪，我也不知道，可能是textview的问题。还有问个问题像问下大佬，就是模块里的资源文件可以直接引用吗？因为之前都是使用lsposed写，对注入原理不是特别懂，还是说得像lsposed那样直接想办法注入到宿主里面？怎么注入呢？希望大佬有空的话回下，感谢大佬

**Comment by orzlenmo** [comment]
已解决，用正常开发注入资源方式，弄好了。感谢大佬前面的回答
